### ISSUE TITLE
More than 8 PS3 Eye Cameras / Virtual Cameras

### ISSUE THREAD

**Issue by dolldanivr** [Timocop/PSMoveServiceEx#1]
Just wondering if theres any way you could support 10-12 pseye cameras somewhere down the line, or if its possible to somehow get it to work right now. I'm trying to get very accurate tracking of a larger room. Thanks in advance!

**Comment by Timocop** [comment]
That would be possible yes later on. But, you probably don't want more than 8 PSeyes. That would be a high amount of USB Bandwidth your PCIe cards probably wont handle that, same with CPU usage when using more than 2 controllers with this amount.

**Comment by Timocop** [comment]
You wont get super accurate tracking by adding more cameras. Theres more factors than more points of view. Like lens distortion, camera resolution, usage of the calibration mat, color detection etc.

**Comment by dolldanivr** [comment]
thank you for your response, I realised the tracking issues im having is that im using the newer model for ps4 rather than the ps3, so unless theres a way to fix drift with ps4 controllers, which I assume there isnt because its a hardware issue since ps4 model doesnt have magnometer, then im just gonna have to get some used controllers of the ps3 variety with magnometer. Thank you for your time! I very much love this fork of psmoveservice! have a good day!

**Comment by Timocop** [comment]
Sadly, there is no way to fix PSmove controller yaw drift without the magnetometer. Be careful buying PS3 PSmove controllers! The newer versions of PS3 PSmove controllers also do not have magnetometers. Check their serial number on the back. If they start with a G, 0, 1 or 2 they will mostly likely have a magnetometers, if not, they do not.

But not all hope is lost for people with magnetometer-less controllers.
Eventually i will get around implemented OwOtrack/SlimeVR into PSMoveServiceEx. So you can use your Phone with either an LED ball or the colored display as a tracker. This will also get rid of manual magnetometer calibration and magnetic drift. Since PSmove IMU is quite... meh.

**Comment by Timocop** [comment]
Im closing this. There probably wont be more than 8 cameras supported. Instead, 1080p resolutions _(instead of 480p and 240p)_ might be added in the future for better tracking quality for webcams.
