### ISSUE TITLE
How to track head in PSMoveServiceEx

### ISSUE THREAD

**Issue by CannedToes** [Timocop/PSMoveServiceEx#13]
Hello,
I am having a problem with the tracking on virtual HDM's on this, I don't know how to do it properly is the real problem I think...
So I'm trying to setup a psmovecontroller that I can attach to my PSVR for positional tracking with my camera, but the only problem is I can't set the virtual HMD color to the same color as my PSMoveController I have paired and I am wanting to use as the virtual HMD positional tracker, so what do I do?

Also on that note, does this software have support for tracking the Lights already on the PSVR?
Thank You!

**Comment by Timocop** [comment]
What hardware are you using?
 - HMD (Virtual / Morpheus)
 - Controllers (PS3 Gen1 / PS3 Gen2 / PS4)
 - Cameras (Webcam / PSEyes) and how many.

What driver are you using (SteamVR)?
 - PSMS VRBridge
 - D4VR
 - iVRy
 - Other?

**Comment by CannedToes** [comment]
Hello again,

Hardware wise:
I am using a Virtual HMD (I think? what is Morpheus?)
With 2 PS3 Gen1 Move Controllers and 1 PS4 Move Controller that I am trying to setup for HMD Positional Tracking
I have 1 PSEye that I am using

Software wise:
I am trying to use the PSMS VRBridge with Trinus PSVR software but please tell me if theres any other software I should use,

Thank you!

**Comment by Timocop** [comment]
Morpheus is the Sony PSVR Headset. Virtual HMD are anything else (e.g PhoneVR).
If you using a Phone for VR, you can just attach a colored ping pong ball onto your Phone HMD to achieve positional tracking.
iVRy for example uses this approach.

Also sell your PS4 PSmove controller and buy another uses PS3 Gen1 controller it does not have a magnetometer and causes drift. Unless you want to use your Phone Gyro for HMD rotation which works as well.
Not only that but also you are just using 1 Camera, which is not recommended. For good tracking you need at least 2 Cameras using triangulation instead of measuring bulb size which is very very very inaccurate.

I dont think Trinus PSVR is even maintained anymore (Personaly i had very bad experiance with their software). Try out iVRy, i have been following that developer for a while and he is doing some insane work on his software. If you want something more freeware, there is also Github repos for PhoneVR and PSMS tracking.
Such as this one [https://github.com/HadesVR/HadesVR](https://github.com/HadesVR/HadesVR)
And [https://github.com/ShootingKing-AM/PhoneVR](https://github.com/ShootingKing-AM/PhoneVR
)

**I do not recommend using PSVR (Headset and External Processor) for PCVR. It is still very hacky and in some cases it still doesnt work for some people. PhoneVR in the other hand has made a lot of progress and is easier to setup and better quality! SO just use PhoneVR with PSmoves instead!**

**Comment by CannedToes** [comment]
Hello again,
I don't have that great of a phone to use for PhoneVR so I don't really want to do that, and I can't really sell the PSMoveControllers, that's why i'm trying to get the PSVR to work but I thought it didn't with this software so I was trying to use the virtual method, how do I activate and use Morpheus? (Also I just wanted to try with 1 Camera but I think eventually I will get another camera for the setup if I find it enjoyable.

**Comment by Timocop** [comment]
If you are using PSMS VR-Bridge for SteamVR you can edit the config file to replace the PSVR HMD positional and orientation tracking with a PSmove controller. 
See [https://github.com/HipsterSloth/PSMoveSteamVRBridge/wiki/Steam-VR-Setup#hmd-controller-3rd-controller-filtering](https://github.com/HipsterSloth/PSMoveSteamVRBridge/wiki/Steam-VR-Setup#hmd-controller-3rd-controller-filtering)
But you might want to use one of your PS3 Gen1 controllers because they use a magnetometer to correct yaw drift.
Otherwise your HMD will drift in yaw slowly and you have to re-center it every time.

Normally you don't need to do this. PSMoveService should detect the glowing PSVR HMD pattern on the headset itself (if you set it up correctly). However, i can't help you with that, i do not own a PSVR HMD.

**Comment by CannedToes** [comment]
I already have the rotational tracking on the PSVR working with IVRY, now I just want to use one of my controllers for positional tracking, how do I do that?

**Comment by Timocop** [comment]
For that you probably need FreePie/FreeTrack and PSMoveServiceFreePieBrdige to translate the controller position to your HMD. But i can not help you with this because i have never done it nor do i have a PSVR headset. You have to ask iVRy support for this or the Driver4VR community.

**Comment by CannedToes** [comment]
Ok, will contact them, thank you!
