### ISSUE TITLE
pairing issue

### ISSUE THREAD

**Issue by idkwhattoget** [Timocop/PSMoveServiceEx#38]
everytime i try to pair a ps move controller, it gets to verifying connection then it goes back to attempting connection
trying to use a different bluetooth adapter just makes it not connect at all
this was working before idk why its no longer working

**Comment by Timocop** [comment]
please upload your log and list your hardware

**Comment by nobody324324123** [comment]
logs:
https://pastebin.com/b73MaKen psmoveconfigtool logs
https://pastebin.com/tVGVN1xy psmoveservice logs

hardware: 
onboard bluetooth adapter
psmove with the model number of CECH-ZCM1E and the serial number of 030071907010 (im not sure about this though because there is a barcode above it so it might just be the barcode number)

forgot to say this but that bluetooth adapter i mentioned does work, it just results in the same thing
it says microsoft on it and windows identifies it as "Microsoft Nano Transreciever v1.0"

**Comment by nobody324324123** [comment]
also found out that my other psmove works

**Comment by Timocop** [comment]
Did you use Legacy PSMS before PSMS-EX? Remove all "Motion Controller" from your Bluetooth settings and factory reset PSMS-EX configs. Then pair again and upload the new log please thanks!

**Comment by nobody324324123** [comment]
yes i did use legacy psmoveservice before psmoveservice ex, and where do i factory reset the configs

**Comment by Timocop** [comment]
Either using going in ``%AppData%/PSMoveService`` and removing every config file or just download Virtual Device Manager and do it from the UI.
![PSMSVirtualDeviceManager_UO6UfMEgDD](https://github.com/Timocop/PSMoveServiceEx/assets/22834512/5400a7a9-d0e2-4c70-bcc6-6e552916c814)

**Comment by nobody324324123** [comment]
ok i can pair it now, its either because of the new update or factory resetting psmoveservice

logs:
https://pastebin.com/9wgREdNr psmoveservice
https://pastebin.com/Av5Uxp8q psmoveserviceconfigtool
