### ISSUE TITLE
Virtual HMD again :p

### ISSUE THREAD

**Issue by SanyaMine** [Timocop/PSMoveServiceEx#4]
In update 0.14.2, tracking of Virtual HMD gets a bit laggy?

Color tracking is fine though, changing the Positional Filter from "LowPassOptical" to "PositionKalman" helps. Tracking gets smoother but introduces some more issues. For example, when it loses tracking with "PositionaKalman" in Pistol Whip (when I cover up the ping pong ball with my hands), I can't duck quickly enough because Virtual HMD tracking has latency.

**Comment by Timocop** [comment]
How many devices are connected? (Controllers etc.)
How many cameras?
What camera fps are you running?
Does the same thing happen with PSMS-EX v0.13?
Test your camera stability with https://github.com/Timocop/PSMoveServiceEx-Fixer/releases

**Comment by k0y4v2** [comment]
1. 2 controllers and 1 Virtual HMD
2. 2 Cameras
3. Depends, sometimes 50 with 640x480 res and sometimes 320x240 with 100fps, but it happens in all of those
4. Nope, it works fine in previous versions, with no issues at all (except for 0.14.0). In 0.14.2, however, controller tracking is totally fine, but not the tracking of Virtual HMD
5. it's a bit meh due to the lack of USB bandwidth, around 50fps with 640x480 50hz, but in the "test_camera.exe" there are Virtual Trackers that I did not create that don't exist in PsMoveServiceConfigTool.

![VirtualTracker](https://user-images.githubusercontent.com/35292248/162998434-ee57293f-33e0-4065-9106-a6c3a3c79417.png)

**Comment by Timocop** [comment]
Do you mix 480p with 240p? I dont recommend running 240p tracking gets snappy and the tracking distance is shorter.
Ill try to reproduce the problem.

**Comment by k0y4v2** [comment]
Sometimes I play with 480p, sometimes with 240p, my room is so small that I can barely notice any difference, in rhytm games I prefer faster tracking instead, 0.14.2 update however improved the tracking a lot, and I can get S rank in beat saber even with 240p :D

**Comment by Timocop** [comment]
Do you use D4VR? The issue may be caused by a slow HMD polling rate. Set it to 2ms. But if you use D4VR it sets it to 13ms for some reason.
![PSMoveConfigTool_2022-04-12_17-59-08](https://user-images.githubusercontent.com/22834512/163004949-2f63ff8d-1698-4806-a720-144de7e2969e.png)

**Comment by k0y4v2** [comment]
Yea, I use D4VR I'll try that thingie later, thanks

**Comment by Timocop** [comment]
If you use D4VR then it will set it back to 13ms. I removed the polling interval for HMDs and controllers entirely in [v0.14.3](https://github.com/Timocop/PSMoveServiceEx/releases/tag/v0.14.3)
This should work for you.

**Comment by Timocop** [comment]
> but in the "test_camera.exe" there are Virtual Trackers that I did not create that don't exist in PsMoveServiceConfigTool.

Ignore the virtual cameras in ``test_cameras.exe`` if you dont use them.

> Depends, sometimes 50 with 640x480 res and sometimes 320x240 with 100fps, but it happens in all of those

You can run PSeyes at 240p up to 183Hz without much USB bandwidth. But if you use D4VR, i recommend ~160Hz because the maximal D4VR fps is around ~160. _(You might wanna change D4VR fps to 160 in ``General Settings`` if you run +90Hz cameras)_

If you use 480p id say crank up the controller prediction. This will improve responsiveness of controllers on lower camera Hz or smoothing filters.
