### ISSUE TITLE
[feature request] ability to use regular webcam and phones instead of pseye camera.

### ISSUE THREAD

**Issue by tails101** [Timocop/PSMoveServiceEx#45]
Well this is pretty much what the title say.
It would be nice to use regular webcams or phone camera to replace the pseye camera for tracking.
I think this is interesting in the long run to add compatibility.

**Comment by picoshmit** [comment]
that`s what virtual trackers are for

**Comment by tails101** [comment]
> that`s what virtual trackers are for

I didn't see anything about it sorry. Does it allow multicam setup?
Lots of the documentation goes to the old repository.

**Comment by Timocop** [comment]
This is already possible since PSMoveServiceEx came out years ago. You have to use the extension **Virtual Device Manager** app. Go to the Wiki how to install it and also see all compatible devices. IP Webcams are not recommended due to most being paywalled, have missing features or are downright terrible in quality or latency. Get Webcams, PS4 Camera or PSEyes instead.
